name: PR Labeler

on:
  pull_request:
    types: [opened]

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Label PR based on branch
        uses: actions/github-script@v7
        with:
          script: |
            const branchName = context.payload.pull_request.head.ref;
            console.log('Branch name:', branchName);
            
            let labelToAdd = null;
            
            if (branchName.startsWith('bug/')) {
              labelToAdd = 'bug';
            } else if (branchName.startsWith('docs/')) {
              labelToAdd = 'documentation';
            } else if (branchName.startsWith('feature/')) {
              labelToAdd = 'enhancement';
            }
            
            console.log('Label to add:', labelToAdd);
            
            if (labelToAdd) {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.pull_request.number,
                labels: [labelToAdd]
              });
              console.log(`Added label: ${labelToAdd}`);
            } else {
              console.log('No matching label found');
            }
